-- 川鹏2号 / WHITIN Amazon 广告「已订阅报告」每日落地表 (advertising.amazon.com/reporting)
-- 与 core.campaign_daily / core.campaign_placement_daily 区分：
--   现有 campaign_* 是另一套 SP-API/ETL 管线(英文列 + attribution_status 等)，
--   本批是 reporting 控制台「已订阅的报告」原始中文导出，列结构不同，独立建表。
-- 5 份报告列结构各不相同，分别建表。30D 报告为每日全量 30 天窗口 → 主键 upsert 取最新版本。
-- 命名沿用 BA 风格：core.subscribed_<维度>_daily

CREATE SCHEMA IF NOT EXISTS core;

-- 共享指标列片段（广告位/搜索词/推广的商品/CPO 四份指标一致，28 列）
-- impressions ... detail_page_view_rate_pct

-- ============ 1. 广告活动 30D 日期 ============
DROP TABLE IF EXISTS core.subscribed_campaign_daily CASCADE;
CREATE TABLE core.subscribed_campaign_daily (
  account_id              text        NOT NULL,
  account_name            text,
  manager_account         text,
  ad_product              text,
  campaign_id             text        NOT NULL,
  campaign_name           text,
  global_campaign_id      text,
  budget_currency         text,
  stat_date               date        NOT NULL,
  impressions             bigint,
  viewable_impressions    bigint,
  clicks                  bigint,
  ctr_pct                 numeric(10,4),
  vctr_pct                numeric(10,4),
  cost                    numeric(18,4),
  purchases               bigint,
  new_to_brand_purchases  bigint,
  cost_per_purchase       numeric(18,4),
  new_to_brand_cost_per_purchase numeric(18,4),
  sales                   numeric(18,4),
  long_term_sales         numeric(18,4),
  roas                    numeric(10,4),
  long_term_roas          numeric(10,4),
  source_file_name        text        NOT NULL,
  source_file_hash        char(64)    NOT NULL,
  imported_at             timestamptz NOT NULL DEFAULT now(),
  report_type             text        NOT NULL DEFAULT 'campaign',
  PRIMARY KEY (account_id, campaign_id, stat_date)
);
CREATE INDEX IF NOT EXISTS idx_sub_campaign_date ON core.subscribed_campaign_daily (stat_date);

-- ============ 2. 广告位 30D 日期 ============
DROP TABLE IF EXISTS core.subscribed_placement_daily CASCADE;
CREATE TABLE core.subscribed_placement_daily (
  budget_currency         text,
  account_id              text        NOT NULL,
  account_name            text,
  portfolio_id            text,
  portfolio_name          text,
  campaign_id             text        NOT NULL,
  campaign_name           text,
  ad_group_id             text        NOT NULL,
  ad_group_name           text,
  placement               text        NOT NULL,
  stat_date               date        NOT NULL,
  impressions             bigint,
  clicks                  bigint,
  ctr_pct                 numeric(10,4),
  cost                    numeric(18,4),
  purchases               bigint,
  sales                   numeric(18,4),
  units                   bigint,
  cost_per_purchase       numeric(18,4),
  purchase_rate_pct       numeric(10,4),
  roas                    numeric(10,4),
  promoted_purchases      bigint,
  promoted_sales          numeric(18,4),
  promoted_units          bigint,
  promoted_cost_per_purchase numeric(18,4),
  promoted_purchase_rate_pct  numeric(10,4),
  promoted_roas           numeric(10,4),
  halo_purchases          bigint,
  halo_sales              numeric(18,4),
  halo_units              bigint,
  new_to_brand_purchases  bigint,
  new_to_brand_sales      numeric(18,4),
  new_to_brand_units      bigint,
  new_to_brand_cost_per_purchase numeric(18,4),
  new_to_brand_purchase_rate_pct  numeric(10,4),
  new_to_brand_roas       numeric(10,4),
  detail_page_views       bigint,
  cost_per_detail_page_view numeric(18,4),
  detail_page_view_rate_pct  numeric(10,4),
  source_file_name        text        NOT NULL,
  source_file_hash        char(64)    NOT NULL,
  imported_at             timestamptz NOT NULL DEFAULT now(),
  report_type             text        NOT NULL DEFAULT 'placement',
  PRIMARY KEY (account_id, campaign_id, ad_group_id, placement, stat_date)
);
CREATE INDEX IF NOT EXISTS idx_sub_placement_date ON core.subscribed_placement_daily (stat_date);

-- ============ 3. 搜索词 30D 日期 ============
DROP TABLE IF EXISTS core.subscribed_search_term_daily CASCADE;
CREATE TABLE core.subscribed_search_term_daily (
  budget_currency         text,
  account_id              text        NOT NULL,
  account_name            text,
  portfolio_id            text,
  portfolio_name          text,
  campaign_id             text        NOT NULL,
  campaign_name           text,
  ad_group_id             text        NOT NULL,
  ad_group_name           text,
  search_term             text        NOT NULL,
  stat_date               date        NOT NULL,
  impressions             bigint,
  clicks                  bigint,
  ctr_pct                 numeric(10,4),
  cost                    numeric(18,4),
  purchases               bigint,
  sales                   numeric(18,4),
  units                   bigint,
  cost_per_purchase       numeric(18,4),
  purchase_rate_pct       numeric(10,4),
  roas                    numeric(10,4),
  promoted_purchases      bigint,
  promoted_sales          numeric(18,4),
  promoted_units          bigint,
  promoted_cost_per_purchase numeric(18,4),
  promoted_purchase_rate_pct  numeric(10,4),
  promoted_roas           numeric(10,4),
  halo_purchases          bigint,
  halo_sales              numeric(18,4),
  halo_units              bigint,
  new_to_brand_purchases  bigint,
  new_to_brand_sales      numeric(18,4),
  new_to_brand_units      bigint,
  new_to_brand_cost_per_purchase numeric(18,4),
  new_to_brand_purchase_rate_pct  numeric(10,4),
  new_to_brand_roas       numeric(10,4),
  detail_page_views       bigint,
  cost_per_detail_page_view numeric(18,4),
  detail_page_view_rate_pct  numeric(10,4),
  source_file_name        text        NOT NULL,
  source_file_hash        char(64)    NOT NULL,
  imported_at             timestamptz NOT NULL DEFAULT now(),
  report_type             text        NOT NULL DEFAULT 'search_term',
  PRIMARY KEY (account_id, campaign_id, ad_group_id, search_term, stat_date)
);
CREATE INDEX IF NOT EXISTS idx_sub_search_term_date ON core.subscribed_search_term_daily (stat_date);

-- ============ 4. 推广的商品 30D 日期 ============
DROP TABLE IF EXISTS core.subscribed_product_daily CASCADE;
CREATE TABLE core.subscribed_product_daily (
  budget_currency         text,
  account_id              text        NOT NULL,
  account_name            text,
  portfolio_id            text,
  portfolio_name          text,
  campaign_id             text        NOT NULL,
  campaign_name           text,
  ad_group_id             text        NOT NULL,
  ad_group_name           text,
  advertised_product_id   text        NOT NULL,
  advertised_product_name text,
  advertised_product_parent_id text,
  advertised_product_brand text,
  advertised_product_category text,
  advertised_product_subcategory text,
  advertised_product_group text,
  advertised_product_sku  text,
  advertised_product_marketplace text,
  stat_date               date        NOT NULL,
  impressions             bigint,
  clicks                  bigint,
  ctr_pct                 numeric(10,4),
  cost                    numeric(18,4),
  purchases               bigint,
  sales                   numeric(18,4),
  units                   bigint,
  cost_per_purchase       numeric(18,4),
  purchase_rate_pct       numeric(10,4),
  roas                    numeric(10,4),
  promoted_purchases      bigint,
  promoted_sales          numeric(18,4),
  promoted_units          bigint,
  promoted_cost_per_purchase numeric(18,4),
  promoted_purchase_rate_pct  numeric(10,4),
  promoted_roas           numeric(10,4),
  halo_purchases          bigint,
  halo_sales              numeric(18,4),
  halo_units              bigint,
  new_to_brand_purchases  bigint,
  new_to_brand_sales      numeric(18,4),
  new_to_brand_units      bigint,
  new_to_brand_cost_per_purchase numeric(18,4),
  new_to_brand_purchase_rate_pct  numeric(10,4),
  new_to_brand_roas       numeric(10,4),
  detail_page_views       bigint,
  cost_per_detail_page_view numeric(18,4),
  detail_page_view_rate_pct  numeric(10,4),
  source_file_name        text        NOT NULL,
  source_file_hash        char(64)    NOT NULL,
  imported_at             timestamptz NOT NULL DEFAULT now(),
  report_type             text        NOT NULL DEFAULT 'product',
  PRIMARY KEY (account_id, campaign_id, ad_group_id, advertised_product_id, stat_date)
);
CREATE INDEX IF NOT EXISTS idx_sub_product_date ON core.subscribed_product_daily (stat_date);

-- ============ 5. 川鹏推广的商品 每日CPO单双计算 (7天窗口, 列结构与推广的商品一致) ============
DROP TABLE IF EXISTS core.subscribed_product_cpo_daily CASCADE;
CREATE TABLE core.subscribed_product_cpo_daily (
  budget_currency         text,
  account_id              text        NOT NULL,
  account_name            text,
  portfolio_id            text,
  portfolio_name          text,
  campaign_id             text        NOT NULL,
  campaign_name           text,
  ad_group_id             text        NOT NULL,
  ad_group_name           text,
  advertised_product_id   text        NOT NULL,
  advertised_product_name text,
  advertised_product_parent_id text,
  advertised_product_brand text,
  advertised_product_category text,
  advertised_product_subcategory text,
  advertised_product_group text,
  advertised_product_sku  text,
  advertised_product_marketplace text,
  stat_date               date        NOT NULL,
  impressions             bigint,
  clicks                  bigint,
  ctr_pct                 numeric(10,4),
  cost                    numeric(18,4),
  purchases               bigint,
  sales                   numeric(18,4),
  units                   bigint,
  cost_per_purchase       numeric(18,4),
  purchase_rate_pct       numeric(10,4),
  roas                    numeric(10,4),
  promoted_purchases      bigint,
  promoted_sales          numeric(18,4),
  promoted_units          bigint,
  promoted_cost_per_purchase numeric(18,4),
  promoted_purchase_rate_pct  numeric(10,4),
  promoted_roas           numeric(10,4),
  halo_purchases          bigint,
  halo_sales              numeric(18,4),
  halo_units              bigint,
  new_to_brand_purchases  bigint,
  new_to_brand_sales      numeric(18,4),
  new_to_brand_units      bigint,
  new_to_brand_cost_per_purchase numeric(18,4),
  new_to_brand_purchase_rate_pct  numeric(10,4),
  new_to_brand_roas       numeric(10,4),
  detail_page_views       bigint,
  cost_per_detail_page_view numeric(18,4),
  detail_page_view_rate_pct  numeric(10,4),
  source_file_name        text        NOT NULL,
  source_file_hash        char(64)    NOT NULL,
  imported_at             timestamptz NOT NULL DEFAULT now(),
  report_type             text        NOT NULL DEFAULT 'cpo',
  PRIMARY KEY (account_id, campaign_id, ad_group_id, advertised_product_id, stat_date)
);
CREATE INDEX IF NOT EXISTS idx_sub_product_cpo_date ON core.subscribed_product_cpo_daily (stat_date);
