DROP TABLE IF EXISTS core.subscribed_placement_daily_snapshot CASCADE;
CREATE TABLE core.subscribed_placement_daily_snapshot (
  snapshot_date date NOT NULL,
  run_id uuid NOT NULL,
  budget_currency text,
  account_id text NOT NULL,
  account_name text,
  portfolio_id text,
  portfolio_name text,
  campaign_id text NOT NULL,
  campaign_name text,
  ad_group_id text NOT NULL,
  ad_group_name text,
  placement text NOT NULL,
  stat_date date NOT NULL,
  impressions bigint,
  clicks bigint,
  ctr_pct numeric(10,4),
  cost numeric(18,4),
  purchases bigint,
  sales numeric(18,4),
  units bigint,
  cost_per_purchase numeric(18,4),
  purchase_rate_pct numeric(10,4),
  roas numeric(10,4),
  promoted_purchases bigint,
  promoted_sales numeric(18,4),
  promoted_units bigint,
  promoted_cost_per_purchase numeric(18,4),
  promoted_purchase_rate_pct numeric(10,4),
  promoted_roas numeric(10,4),
  halo_purchases bigint,
  halo_sales numeric(18,4),
  halo_units bigint,
  new_to_brand_purchases bigint,
  new_to_brand_sales numeric(18,4),
  new_to_brand_units bigint,
  new_to_brand_cost_per_purchase numeric(18,4),
  new_to_brand_purchase_rate_pct numeric(10,4),
  new_to_brand_roas numeric(10,4),
  detail_page_views bigint,
  cost_per_detail_page_view numeric(18,4),
  detail_page_view_rate_pct numeric(10,4),
  report_type text NOT NULL DEFAULT 'placement',
  PRIMARY KEY (snapshot_date, account_id, campaign_id, ad_group_id, placement, stat_date)
);

DROP TABLE IF EXISTS core.subscribed_product_cpo_daily_snapshot CASCADE;
CREATE TABLE core.subscribed_product_cpo_daily_snapshot (
  snapshot_date date NOT NULL,
  run_id uuid NOT NULL,
  report_type text NOT NULL DEFAULT 'cpo',
  ad_group_id text NOT NULL,
  ad_group_name text,
  advertised_product_id text NOT NULL,
  advertised_product_name text,
  advertised_product_parent_id text,
  advertised_product_brand text,
  advertised_product_category text,
  advertised_product_subcategory text,
  advertised_product_group text,
  advertised_product_sku text,
  advertised_product_marketplace text,
  stat_date date NOT NULL,
  impressions bigint,
  clicks bigint,
  ctr_pct numeric(10,4),
  cost numeric(18,4),
  purchases bigint,
  sales numeric(18,4),
  units bigint,
  cost_per_purchase numeric(18,4),
  purchase_rate_pct numeric(10,4),
  roas numeric(10,4),
  promoted_purchases bigint,
  promoted_sales numeric(18,4),
  promoted_units bigint,
  promoted_cost_per_purchase numeric(18,4),
  promoted_purchase_rate_pct numeric(10,4),
  promoted_roas numeric(10,4),
  halo_purchases bigint,
  halo_sales numeric(18,4),
  halo_units bigint,
  new_to_brand_purchases bigint,
  new_to_brand_sales numeric(18,4),
  new_to_brand_units bigint,
  new_to_brand_cost_per_purchase numeric(18,4),
  new_to_brand_purchase_rate_pct numeric(10,4),
  new_to_brand_roas numeric(10,4),
  detail_page_views bigint,
  cost_per_detail_page_view numeric(18,4),
  detail_page_view_rate_pct numeric(10,4),
  budget_currency text,
  account_id text NOT NULL,
  account_name text,
  portfolio_id text,
  portfolio_name text,
  campaign_id text NOT NULL,
  campaign_name text,
  PRIMARY KEY (snapshot_date, ad_group_id, advertised_product_id, stat_date, account_id, campaign_id)
);

DROP TABLE IF EXISTS core.subscribed_search_term_daily_snapshot CASCADE;
CREATE TABLE core.subscribed_search_term_daily_snapshot (
  snapshot_date date NOT NULL,
  run_id uuid NOT NULL,
  account_id text NOT NULL,
  account_name text,
  portfolio_id text,
  portfolio_name text,
  campaign_id text NOT NULL,
  campaign_name text,
  ad_group_id text NOT NULL,
  ad_group_name text,
  search_term text NOT NULL,
  stat_date date NOT NULL,
  impressions bigint,
  clicks bigint,
  ctr_pct numeric(10,4),
  cost numeric(18,4),
  purchases bigint,
  sales numeric(18,4),
  units bigint,
  cost_per_purchase numeric(18,4),
  purchase_rate_pct numeric(10,4),
  roas numeric(10,4),
  promoted_purchases bigint,
  promoted_sales numeric(18,4),
  promoted_units bigint,
  promoted_cost_per_purchase numeric(18,4),
  promoted_purchase_rate_pct numeric(10,4),
  promoted_roas numeric(10,4),
  halo_purchases bigint,
  halo_sales numeric(18,4),
  halo_units bigint,
  new_to_brand_purchases bigint,
  new_to_brand_sales numeric(18,4),
  new_to_brand_units bigint,
  new_to_brand_cost_per_purchase numeric(18,4),
  new_to_brand_purchase_rate_pct numeric(10,4),
  new_to_brand_roas numeric(10,4),
  detail_page_views bigint,
  cost_per_detail_page_view numeric(18,4),
  detail_page_view_rate_pct numeric(10,4),
  report_type text NOT NULL DEFAULT 'search_term',
  budget_currency text,
  PRIMARY KEY (snapshot_date, account_id, campaign_id, ad_group_id, search_term, stat_date)
);

CREATE INDEX IF NOT EXISTS idx_sub_search_term_snap_cmp ON core.subscribed_search_term_daily_snapshot (search_term, stat_date, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_sub_placement_snap_cmp ON core.subscribed_placement_daily_snapshot (placement, stat_date, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_sub_product_cpo_snap_cmp ON core.subscribed_product_cpo_daily_snapshot (advertised_product_id, stat_date, snapshot_date);

