#!/usr/bin/env python3
"""
自动导出浏览器 cookies 为 Netscape 格式（yt-dlp 兼容）

── 为什么 Python 不能像插件一样读取 Chrome cookies ─────────────────────────
Chrome 插件 "Get cookies.txt LOCALLY" 通过 chrome.cookies API 读取，
该 API 运行在 Chrome 内核中，直接返回明文 cookies，无需解密。

Python 运行在 Chrome 外部，面临两道障碍：
  1. 文件锁：Chrome 运行时 SQLite 数据库被锁，无法复制
  2. App-Bound Encryption（Chrome 127+, 2024-07）：
     加密密钥绑定到 Chrome 二进制本身，外部程序无法解密。
     browser_cookie3 / rookiepy / pycookiecheat 在现代 Chrome 上全部失效。

── 可行方案（按推荐顺序）───────────────────────────────────────────────────
  方案A：CDP 远程调试  ← Chrome 运行时可用，无需管理员，推荐
  方案B：yt-dlp       ← 关闭 Chrome 后直接用，最简单
  方案C：手动插件导出  ← 兜底，永远可靠

── 用法 ─────────────────────────────────────────────────────────────────────
  python export_cookies.py bilibili.com
  python export_cookies.py youtube.com --browser edge --cdp-port 9222
"""
import os, sys, json, subprocess, argparse, socket, tempfile
from pathlib import Path

VAULT_ROOT  = Path(r"D:\Download\agent-master")
DEFAULT_OUT = VAULT_ROOT / "cookies.txt"


# ── 工具 ─────────────────────────────────────────────────────────────────────
def is_process_running(name: str) -> bool:
    r = subprocess.run(
        ["tasklist", "/fi", f"imagename eq {name}.exe", "/fo", "csv", "/nh"],
        capture_output=True, text=True)
    return name.lower() in r.stdout.lower()

def is_port_open(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(1)
        return s.connect_ex(("127.0.0.1", port)) == 0

def write_netscape(cookies: list, out_path: Path) -> int:
    """写 Netscape 格式（yt-dlp 兼容）"""
    lines = ["# Netscape HTTP Cookie File", "# Generated by export_cookies.py\n"]
    for c in cookies:
        domain  = c.get("domain", "")
        secure  = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires", 0) or 9999999999)
        lines.append("\t".join([
            domain,
            "TRUE" if domain.startswith(".") else "FALSE",
            c.get("path", "/"),
            secure,
            str(expires),
            c.get("name", ""),
            c.get("value", ""),
        ]))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return len(cookies)


# ── 方案A：CDP 远程调试（推荐）────────────────────────────────────────────────
def method_cdp(domain: str, out_path: Path, cdp_port: int) -> bool:
    """
    通过 Chrome DevTools Protocol 读取 cookies。
    Chrome 直接返回明文，完全绕过 App-Bound Encryption。

    前置条件：Chrome 快捷方式目标末尾加 --remote-debugging-port=9222
    """
    if not is_port_open(cdp_port):
        print(f"  端口 {cdp_port} 未开放。")
        print(f"  一次性配置：右键 Chrome 快捷方式 → 属性 → 目标末尾加：")
        print(f"    --remote-debugging-port={cdp_port}")
        print(f"  重启 Chrome 后再运行此脚本即可。")
        return False

    try:
        import urllib.request, websocket  # pip install websocket-client
    except ImportError:
        print("  缺少依赖：pip install websocket-client")
        return False

    try:
        info = json.loads(
            urllib.request.urlopen(f"http://127.0.0.1:{cdp_port}/json/version", timeout=3).read()
        )
        ws_url = info.get("webSocketDebuggerUrl", "")
        print(f"  已连接：{info.get('Browser', 'unknown')}")

        ws = websocket.create_connection(ws_url, timeout=10)
        ws.send(json.dumps({"id": 1, "method": "Network.getAllCookies", "params": {}}))
        all_cookies = json.loads(ws.recv()).get("result", {}).get("cookies", [])
        ws.close()

        target = domain.lstrip(".")
        filtered = [c for c in all_cookies if target in c.get("domain", "")]

        if not filtered:
            print(f"  未找到 {domain} cookies（可能未登录该网站）")
            return False

        n = write_netscape(filtered, out_path)
        print(f"  ✅ 成功：{n} 条 cookies → {out_path}")
        return True

    except Exception as e:
        print(f"  失败：{e}")
        return False


# ── 方案B：yt-dlp（关闭浏览器后）────────────────────────────────────────────
def method_ytdlp(browser: str, domain: str, out_path: Path) -> bool:
    """
    yt-dlp 在浏览器关闭后可直接读取 cookie 数据库（SQLite 文件解锁）。
    注意：Chrome 127+ 的 App-Bound Encryption 对 yt-dlp 同样有效，
    但 yt-dlp 自己实现了解密逻辑，通过 COM 接口调用 Chrome 解密，
    因此在关闭状态下可以正常工作。
    """
    if is_process_running(browser):
        print(f"  {browser} 正在运行，请关闭后执行此步骤")
        print(f"  关闭 {browser} 后运行：yt-dlp --cookies-from-browser {browser} ...")
        return False

    tmp = Path(tempfile.mktemp(suffix=".txt"))
    print(f"  {browser} 已关闭，尝试 yt-dlp 读取...")
    try:
        subprocess.run(
            ["python", "-m", "yt_dlp",
             "--cookies-from-browser", browser,
             "--cookies", str(tmp),
             "--skip-download", f"https://{domain}"],
            capture_output=True, timeout=30, check=True
        )
        if tmp.exists() and tmp.stat().st_size > 100:
            # 过滤目标域名
            base = domain.split(".")[-2]
            lines = [l for l in tmp.read_text().splitlines()
                     if not l.strip() or base in l or l.startswith("#")]
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text("\n".join(lines), encoding="utf-8")
            print(f"  ✅ 成功 → {out_path}")
            return True
        print("  输出文件为空")
    except Exception as e:
        print(f"  失败：{e}")
    finally:
        tmp.unlink(missing_ok=True)
    return False


# ── 主流程 ────────────────────────────────────────────────────────────────────
def export_cookies(domain: str, browser="chrome",
                   out_path: Path = DEFAULT_OUT, cdp_port=9222) -> bool:
    running = is_process_running(browser)
    print(f"\n目标：{domain}  浏览器：{browser}（{'运行中' if running else '未运行'}）")
    print(f"输出：{out_path}\n")

    for label, fn in [
        ("方案A：CDP 远程调试", lambda: method_cdp(domain, out_path, cdp_port)),
        ("方案B：yt-dlp（需关闭浏览器）", lambda: method_ytdlp(browser, domain, out_path)),
    ]:
        print(f"[{label}]")
        if fn():
            print(f"\n✅ 导出成功！")
            print(f"   yt-dlp 中使用：--cookies \"{out_path}\"")
            return True
        print()

    print(f"""❌ 自动导出失败。

── 方案C：手动导出（最可靠，永远可用）────────────────────────────────
1. 安装 Chrome 插件：
   https://chromewebstore.google.com/detail/cclelndahbckbenkjhflpdbgdldlbecc
2. 登录 {domain}
3. 点击插件图标 → Export as → cookies.txt
4. 保存到：{out_path}

── 为什么 Chrome 127+ 不能用 Python 直接读取 cookies ─────────────────
Chrome 127（2024-07）引入 App-Bound Encryption，将加密密钥绑定到
Chrome 二进制本身。browser_cookie3 / rookiepy 等库在现代 Chrome 上
已全部失效。CDP 方案绕过了加密（Chrome 在 DevTools 里返回明文）。

── 一次性启用 CDP（之后永远自动导出）───────────────────────────────
1. 右键 Chrome 桌面快捷方式 → 属性
2. 目标字段末尾追加（注意有空格）：
     --remote-debugging-port=9222
3. 应用 → 重启 Chrome → 再运行此脚本
""")
    return False


def main():
    parser = argparse.ArgumentParser(description="导出浏览器 cookies（Netscape 格式）")
    parser.add_argument("domain",     nargs="?", default="bilibili.com")
    parser.add_argument("--browser",  default="chrome", choices=["chrome", "edge", "brave"])
    parser.add_argument("--output",   default=str(DEFAULT_OUT))
    parser.add_argument("--cdp-port", type=int, default=9222)
    args = parser.parse_args()
    sys.exit(0 if export_cookies(
        args.domain, args.browser, Path(args.output), args.cdp_port
    ) else 1)


if __name__ == "__main__":
    main()
