#!/usr/bin/env python3
"""把「在售产品.xlsx」核验后写入应用库 amazon_ads 的 app.product_roster。

定位：这是**主数据 / 产品归属基准**，属于应用层，因此落 amazon_ads（不是广告事实库 v2）。
口径：开发端一次性核验 → 直接对外显示。没有「待确认 / 手动新增」状态位。

用法：
  python3 scripts/load_product_roster.py            # 核验 + 写 CSV + 入 RDS
  python3 scripts/load_product_roster.py --dry      # 只核验 + 写 CSV，不碰数据库
"""
from __future__ import annotations

import argparse
import collections
import csv
import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit

import openpyxl

BACKEND_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = BACKEND_ROOT.parent
XLSX = Path("/Users/panjinlong/Downloads/在售产品.xlsx")
OUT_DIR = PROJECT_ROOT / "reference" / "product_mapping"
NORM_CSV = OUT_DIR / "在售产品_规范化.csv"
NAME_MAP_CSV = OUT_DIR / "运营人名组码映射.csv"
ENV_PATH = BACKEND_ROOT / ".env"
ALLOWED_HOSTS = ("127.0.0.1", "localhost")   # 2026-09-30：迁腾讯云后经本机 SSH 隧道访问（旧 .pg.rds.aliyuncs.com 已停用）

ASIN_RE = re.compile(r"/dp/([A-Z0-9]{10})")
STRICT_ASIN = re.compile(r"^[A-Z0-9]{10}$")

# 运营人名 → 运营组码。开发端维护，改这里就是改口径。
# 数据来源：项目长期记忆里已确认的对应关系；未确认的一律留空，不用猜。
PERSON_TO_GROUP = {
    "刘子娟": "ZJ1", "刘贞珍": "ZJ1",
    "阴鑫华": "XH1",
    "林雅婷": "YT1",
    "李丽斌": "LB1",
    "谢丹丹": "DD1",
    "胡雪敏": "XM",      # XM1/XM2 未定，只到前缀
    "王爱菊": "AJ",      # AJ1/AJ2 未定，只到前缀
    "史雨珊": "YS1",
    "林文": "LW",
    "王珍凤": "ZF",
    # 以下 4 位只在「+」后面作为组员出现，从没当过第一责任人 —— 未定组，留空
    "林敏": "",
    "沈玉灵": "",
    "王卓玲": "",
    "郑兰兰": "",
}
SITE_PREFIX = {"美站": "美站", "欧站": "欧站"}

DDL = """
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.operator_name_map (
    person_name TEXT PRIMARY KEY,
    group_code  TEXT,
    note        TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.product_roster (
    roster_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand           TEXT NOT NULL,
    product_code    TEXT NOT NULL,
    category        TEXT NOT NULL,
    size_range      TEXT NOT NULL,
    factory         TEXT NOT NULL,
    parent_asin     TEXT,
    front_url       TEXT,
    rating          NUMERIC(3,1),
    sheet_seq       TEXT,
    is_listed       BOOLEAN NOT NULL DEFAULT FALSE,
    operator_text   TEXT NOT NULL,
    operator_names  TEXT[] NOT NULL DEFAULT '{}',
    operator_groups TEXT[] NOT NULL DEFAULT '{}',
    owner_group     TEXT,
    owner_name      TEXT,
    site_scope      TEXT,
    in_stock        BOOLEAN NOT NULL DEFAULT TRUE,
    verified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_file     TEXT NOT NULL,
    source_sheet    TEXT NOT NULL,
    source_row      INT  NOT NULL,
    row_hash        CHAR(64) NOT NULL,
    UNIQUE (brand, product_code)
);
CREATE INDEX IF NOT EXISTS idx_roster_asin   ON app.product_roster (parent_asin);
CREATE INDEX IF NOT EXISTS idx_roster_owner  ON app.product_roster (owner_group);
CREATE INDEX IF NOT EXISTS idx_roster_brand  ON app.product_roster (brand);

COMMENT ON TABLE app.product_roster IS
  '在售产品主数据（开发端核验产物，权威基准）。来源：在售产品.xlsx。无「待确认」状态位。';
"""


def load_dsn() -> dict:
    raw = ""
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        if line.startswith("DATABASE_URL="):
            raw = line.split("=", 1)[1].strip()
            break
    if not raw:
        raise SystemExit("backend/.env 里没有 DATABASE_URL")
    p = urlsplit(raw)
    if p.hostname not in ALLOWED_HOSTS:
        raise SystemExit(f"拒绝执行：host={p.hostname} 不是 RDS 主机")
    q = parse_qs(p.query)
    return {"host": p.hostname, "port": str(p.port or 5432), "user": unquote(p.username or ""),
            "password": unquote(p.password or ""), "dbname": p.path.lstrip("/"),
            "sslmode": (q.get("sslmode") or ["verify-full"])[-1],
            "sslrootcert": (q.get("sslrootcert") or [""])[-1]}


def psql(dsn: dict, sql: str, stdin: str | None = None) -> tuple[int, str, str]:
    env = os.environ.copy()
    env["PGPASSWORD"] = dsn["password"]
    env["PGSSLMODE"] = dsn["sslmode"]
    if dsn["sslrootcert"]:
        env["PGSSLROOTCERT"] = dsn["sslrootcert"]
    env["PGCONNECT_TIMEOUT"] = "15"
    cmd = ["psql", "-w", "-h", dsn["host"], "-p", dsn["port"], "-U", dsn["user"],
           "-d", dsn["dbname"], "-X", "-q", "-v", "ON_ERROR_STOP=1"]
    if stdin is None:
        cmd += ["-c", sql]
    else:
        cmd += ["-f", "-"]
    proc = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=180,
                          input=stdin if stdin is not None else None)
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


def read_xlsx() -> list[dict]:
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    out: list[dict] = []
    for ws in wb.worksheets:
        rows = list(ws.iter_rows(values_only=True))
        hdr = [("" if c is None else str(c).replace("\n", " ").strip()) for c in rows[0]]

        def col(*keys: str):
            for i, h in enumerate(hdr):
                if any(k in h for k in keys):
                    return i
            return None

        idx = {
            "seq": col("序号"), "code": col("款号"), "cat": col("分类"),
            "link": col("链接"), "rating": col("评分"), "size": col("码段"),
            "factory": col("工厂"), "ops": col("运营小组"),
        }
        for ri, r in enumerate(rows[1:], start=2):
            raw_code = r[idx["code"]] if idx["code"] is not None else None
            if raw_code is None or str(raw_code).strip() == "":
                continue
            link = str(r[idx["link"]] or "").strip()
            link = link.replace("://newtab@", "://")
            m = ASIN_RE.search(link)
            rating = r[idx["rating"]] if idx["rating"] is not None else None
            try:
                rating_v = float(str(rating).strip()) if rating not in (None, "") else None
            except ValueError:
                rating_v = None
            out.append({
                "brand": ws.title, "sheet_seq": str(r[idx["seq"]]).strip() if r[idx["seq"]] is not None else "",
                "product_code": str(raw_code).strip(),
                "category": str(r[idx["cat"]] or "").strip(),
                "front_url": link, "parent_asin": m.group(1) if m else "",
                "rating": rating_v, "size_range": str(r[idx["size"]] or "").strip(),
                "factory": str(r[idx["factory"]] or "").strip(),
                "operator_text": str(r[idx["ops"]] or "").replace("\n", " ").strip(),
                "source_sheet": ws.title, "source_row": ri,
            })
    wb.close()
    return out


def parse_operators(text: str) -> tuple[list[str], list[str], str | None]:
    """把「负责的运营小组」原文拆成人名序列 + 组码序列 + 站点。

    关键：必须按**出现位置**取人名（第一个 = 第一责任人），不能按名字长度排序找 —— 否则
    「胡雪敏+林敏+沈玉灵」会被重排成「沈玉灵/胡雪敏/林敏」，主导人就判错了。
    用 `re.finditer` 做最左最长匹配，天然保序。
    """
    site = None
    hits_site = [label for pre, label in SITE_PREFIX.items() if pre in text]
    if hits_site:
        site = "/".join(dict.fromkeys(hits_site))   # 一行可能同时挂美站+欧站
    cleaned = text
    for pre in SITE_PREFIX:
        cleaned = cleaned.replace(pre, " ")

    name_re = re.compile("|".join(sorted((re.escape(n) for n in PERSON_TO_GROUP), key=len, reverse=True)))
    found: list[str] = []
    for token in re.split(r"[、,;/\s+＋]+", cleaned):
        token = token.strip()
        if not token:
            continue
        hits = [m.group(0) for m in name_re.finditer(token)]
        found.extend(hits or [token])   # 匹配不到已知人名时，原样保留以便暴露出来
    groups = [PERSON_TO_GROUP.get(n, "") for n in found]
    return found, groups, site


def build(rows: list[dict]) -> tuple[list[dict], list[dict]]:
    recs, issues = [], []
    for r in rows:
        names, groups, site = parse_operators(r["operator_text"])
        owner_name = names[0] if names else None
        owner_group = next((g for g in groups if g), None)
        unknown = [n for n, g in zip(names, groups) if not g]
        if unknown:
            issues.append({"kind": f"组员无独立组码（不影响主导组）", "brand": r["brand"],
                           "code": r["product_code"], "detail": ", ".join(sorted(set(unknown)))})
        if not owner_group:
            issues.append({"kind": "★ 无法确定主导组", "brand": r["brand"],
                           "code": r["product_code"], "detail": r["operator_text"]})
        if not r["parent_asin"]:
            issues.append({"kind": "无前台链接/ASIN（未上架）", "brand": r["brand"],
                           "code": r["product_code"], "detail": r["front_url"][:60]})
        if r["rating"] is None:
            issues.append({"kind": "缺评分", "brand": r["brand"], "code": r["product_code"], "detail": ""})
        if not r["sheet_seq"]:
            issues.append({"kind": "缺序号（追加行）", "brand": r["brand"], "code": r["product_code"], "detail": ""})
        r2 = dict(r)
        r2.update({"operator_names": names, "operator_groups": groups, "owner_name": owner_name,
                   "owner_group": owner_group, "site_scope": site,
                   "is_listed": bool(r["parent_asin"]),
                   "row_hash": hashlib.sha256(
                       "|".join([r["brand"], r["product_code"], r["category"], r["size_range"],
                                 r["factory"], r["parent_asin"], r["operator_text"]]).encode()).hexdigest()})
        recs.append(r2)
    return recs, issues


def write_csvs(recs: list[dict]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cols = ["brand", "product_code", "category", "size_range", "factory", "parent_asin",
            "front_url", "rating", "sheet_seq", "is_listed", "operator_text",
            "operator_names", "operator_groups", "owner_group", "owner_name", "site_scope"]
    with NORM_CSV.open("w", encoding="utf-8-sig", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(cols)
        for r in recs:
            w.writerow([
                r["brand"], r["product_code"], r["category"], r["size_range"], r["factory"],
                r["parent_asin"], r["front_url"], "" if r["rating"] is None else r["rating"],
                r["sheet_seq"], "Y" if r["is_listed"] else "N", r["operator_text"],
                "|".join(r["operator_names"]), "|".join(r["operator_groups"]),
                r["owner_group"] or "", r["owner_name"] or "", r["site_scope"] or "",
            ])
    with NAME_MAP_CSV.open("w", encoding="utf-8-sig", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["person_name", "group_code", "status", "note"])
        for name, grp in sorted(PERSON_TO_GROUP.items()):
            w.writerow([name, grp, "已核验" if grp else "组员",
                        "" if grp else "只在「+」后作为组员出现，未当过第一责任人，故不单独设组码"])


def load(recs: list[dict], dsn: dict) -> None:
    code, out, err = psql(dsn, DDL)
    if code != 0:
        raise SystemExit(f"建表失败：{err}")

    # 说明：不用 `psql -f -` 里的 COPY ... FROM STDIN，因为 `\.` 终止符在管道输入下会被当成数据行。
    # 改为把数据写成临时 CSV，再用客户端侧 `\copy` 灌入。
    import tempfile

    cols = ("brand, product_code, category, size_range, factory, parent_asin, front_url, rating, "
            "sheet_seq, is_listed, operator_text, operator_names, operator_groups, owner_group, "
            "owner_name, site_scope, source_file, source_sheet, source_row, row_hash")

    def q(v):
        if v is None or v == "":
            return ""
        s = str(v).replace('"', '""')
        return f'"{s}"'

    tmp = Path(tempfile.mkdtemp(prefix="roster_")) / "roster.csv"
    with tmp.open("w", encoding="utf-8", newline="") as fh:
        for r in recs:
            fh.write(",".join([
                q(r["brand"]), q(r["product_code"]), q(r["category"]), q(r["size_range"]),
                q(r["factory"]), q(r["parent_asin"]), q(r["front_url"]),
                q("" if r["rating"] is None else r["rating"]), q(r["sheet_seq"]),
                q("t" if r["is_listed"] else "f"), q(r["operator_text"]),
                q("{" + ",".join('"' + n.replace('"', '\\"') + '"' for n in r["operator_names"]) + "}"),
                q("{" + ",".join('"' + g + '"' for g in r["operator_groups"]) + "}"),
                q(r["owner_group"]), q(r["owner_name"]), q(r["site_scope"]),
                q(XLSX.name), q(r["source_sheet"]), q(r["source_row"]), q(r["row_hash"]),
            ]) + "\n")

    stmts = ["BEGIN;", "TRUNCATE app.product_roster;", "TRUNCATE app.operator_name_map;"]
    for name, grp in sorted(PERSON_TO_GROUP.items()):
        g = "NULL" if not grp else "'" + grp.replace("'", "''") + "'"
        note = "'只在组员位置出现，未当过第一责任人，故不单独设组码'" if not grp else "''"
        stmts.append(f"INSERT INTO app.operator_name_map(person_name,group_code,note) "
                     f"VALUES ('{name}', {g}, {note});")
    stmts.append(f"\\copy app.product_roster ({cols}) FROM '{tmp}' WITH (FORMAT csv)")
    stmts.append("COMMIT;")

    # `\copy` 是 psql 元命令，必须走 -f -（stdin 脚本），不能塞进 -c
    code, out, err = psql(dsn, "", stdin="\n".join(stmts) + "\n")
    if code != 0:
        raise SystemExit(f"灌库失败：{err}")
    tmp.unlink(missing_ok=True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry", action="store_true", help="只核验与写 CSV，不碰数据库")
    args = ap.parse_args()

    rows = read_xlsx()
    recs, issues = build(rows)
    write_csvs(recs)

    print(f"读取 {XLSX.name}：{len(recs)} 个产品行")
    print("  按品牌:", dict(collections.Counter(r['brand'] for r in recs)))
    print(f"  已上架（有 ASIN）: {sum(1 for r in recs if r['is_listed'])}")
    print(f"  唯一父 ASIN: {len({r['parent_asin'] for r in recs if r['parent_asin']})}")
    print(f"  规范化 CSV -> {NORM_CSV}  ({len(recs)} 行)")
    print(f"  人名映射 CSV -> {NAME_MAP_CSV}")
    print()
    print("核验提示（非阻塞，供人工参考）:")
    by_kind = collections.Counter(i["kind"] for i in issues)
    for kind, n in by_kind.most_common():
        print(f"  - {kind}: {n} 条")
    for i in issues:
        if i["kind"].startswith("★"):
            print(f"      {i['brand']}·{i['code']}: {i['detail']}")

    if args.dry:
        print("\n--dry：未写入数据库。")
        return 0

    dsn = load_dsn()
    print(f"\n写入 {dsn['user']}@{dsn['host']}:{dsn['port']}/{dsn['dbname']}")
    load(recs, dsn)
    ok, out, err = psql(dsn, "SELECT count(*), count(parent_asin), count(DISTINCT owner_group) "
                             "FROM app.product_roster;")
    print(f"app.product_roster: 总行/有ASIN/不同运营组 = {out}")
    ok, out, err = psql(dsn, "SELECT count(*) FROM app.product_roster WHERE owner_group IS NULL;")
    print(f"  未定主导组: {out} 行")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
