CREATE SCHEMA IF NOT EXISTS iam;

CREATE TABLE IF NOT EXISTS iam.roles (
    role_code VARCHAR(32) PRIMARY KEY,
    display_name VARCHAR(64) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO iam.roles (role_code, display_name, description) VALUES
    ('super_admin', '超级管理员', '系统级账号与身份管理'),
    ('management', '管理层', '老板与运营主管同一层级'),
    ('operator', '运营', '各运营个人账号')
ON CONFLICT (role_code) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS iam.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(320),
    password_hash TEXT NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    role_code VARCHAR(32) NOT NULL REFERENCES iam.roles(role_code),
    operator_code VARCHAR(32),
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT users_status_check CHECK (status IN ('active', 'disabled')),
    CONSTRAINT users_operator_role_check CHECK (
        (role_code = 'operator' AND operator_code IS NOT NULL AND BTRIM(operator_code) <> '')
        OR
        (role_code <> 'operator' AND operator_code IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_uidx
    ON iam.users (LOWER(username));

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx
    ON iam.users (LOWER(email))
    WHERE email IS NOT NULL;
