CREATE TABLE IF NOT EXISTS iam.user_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES iam.users(user_id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ,
    CONSTRAINT user_sessions_expiry_check CHECK (expires_at > created_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS user_sessions_token_hash_uidx
    ON iam.user_sessions (token_hash);

CREATE INDEX IF NOT EXISTS user_sessions_user_active_idx
    ON iam.user_sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;
